data_preprocess:
  original_dataset: "./original_chest_xray"
  new_dataset: "./chest_xray"
  image_size: 256

train:
  num_classes: 3
  num_workers: 10
  num_epochs: 100
  weight_decay: 0.0001
  batch_size: 700
  lr: 0.0001
  data_split_seed: 2076770559